### PR TITLE
Update version to reflect original package version

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by gadicc** [comment]
I love PRs :)  Yes I agree, this is a better versioning scheme.  Thanks a lot!

**Comment by gadicc** [comment]
Oops, my bad.  Reopening so I can merge.

**Comment by gadicc** [comment]
Note, Atmosphere needs the version to be in the standard semantic versioning format, so I made it "3.0.83-7" instead of .7.  Thanks :>

**Comment by dandv** [comment]
Nice, now I'll have to update all my Atmosphere packages to use that versioning format :)

**Comment by gadicc** [comment]
Seems to be something new.  I see there's an atmosphere package from 15 days ago with a "v1.5.1.1", but when I tried to release with that format it was rejected with a link to http://semver.org/.  So yeah I guess every time you update a package :)

**Comment by dandv** [comment]
More discussion [here](https://groups.google.com/d/msg/meteor-talk/873tSoIWHuU/wl1Lfz8xRzkJ) including reports that Atmoshpere rejects dashes in version numbers.

**Pull request merged**
